openapi: 3.0.3
info:
  title: forPlapoApps v2 API
  description: |-
    This is a swagger for forPlapoApps v2 server.
  termsOfService: http://swagger.io/terms/
  license:
    name: higakijin
    url: https://twitter.com/higakijin
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8000
tags:
  - name: user
    description: Operations about user
paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: cleg2hb9t0000yx3ja5s1tk57
        createdAt:
          type: string
          example: 2023-02-22T19:27:04.530Z
        updatedAt:
          type: string
          example: 2023-02-22T19:27:04.530Z
        name:
          type: string
          example: higakijin
        email:
          type: string
          example: higakijin@example.com
        firebaseId:
          type: string
          example: lsRI4iAjx2Pka2A1qbCQknFcLzk1
        imageUrl:
          type: string
          example: https://higakijin.jpg
